case $TERM in
xterm*|rxvt*)
PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}[`basename ${PWD}`]\007"'
;;
screen*)
PROMPT_COMMAND='echo -ne "\033k\033\134\033k${HOSTNAME}[`basename ${PWD}`]\033\134"'
;;
*)
    ;;
esac
eval `dircolors ~/.dir_colors`
alias ls="ls --color=auto"
export PATH=${PATH}:~/bin
