case $TERM in
xterm*|rxvt*)
PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}[`basename ${PWD}`]\007"'
;;
screen*)
PROMPT_COMMAND='echo -ne "\033k\033\134\033k${HOSTNAME}[`basename ${PWD}`]\033\134"'
;;
*)
    ;;
esac

if [ ! -f ~/.dir_colors ]; then
        echo "Setting Default dir_colors"
        dircolors -p > ~/.dir_colors
fi

eval `dircolors ~/.dir_colors`
alias ls="ls --color=auto"
alias rmbin="rm ./*.o; rm ./*.so; rm ./*.a"
export PATH=${PATH}:~/bin
